server:
  port: 8022
spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer_a
  #配置rabbitMq 服务器
  rabbitmq:
    host: 42.193.39.59
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    virtual-host: