server:
  port: 8081
  servlet:
    context-path: /demo
    encoding:
      charset: UTF-8
spring:
  jackson:
    #前端页面传Date值时格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 静态文件请求匹配方式
  mvc:
    static-path-pattern: /**
  #thymelea模板配置
  thymeleaf:
    # templates文件夹的路径
    prefix: classpath:/templates/
    # templates中的所有文件后缀名，如/templates/main.html
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 在开发时建议将spring.thymeleaf.cache设置为false，否则会有缓存，导致页面没法及时看到更新后的效果
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
    # 修改默认的静态寻址资源目录
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

